### ISSUE TITLE
City name overlaps the sunset time in 24h mode

### ISSUE THREAD

**Issue by shadow303** [mattrossman/forecaswatch2#19]
![IMG_20191009_122240_1](https://user-images.githubusercontent.com/40325688/66572520-c7f80080-eb79-11e9-81b0-927c392d4707.jpg)
![IMG_20191010_145548_1](https://user-images.githubusercontent.com/40325688/66572521-c7f80080-eb79-11e9-88ba-3f6ad1134b75.jpg)

**Comment by mattrossman** [comment]
First of all, it's fucking cool seeing people using this in the wild 😄

Good catch, I haven't encountered cities with such long names I suppose. Trying to think of the best way to size the textbox, since there's also some uncertainty on the left side (Fahrenheit temps go into triple digits). Maybe I could calculate the available space based on the current size of the left and right text boxes.

**Comment by mattrossman** [comment]
I'm really curious about the city names in your pics, because when I try overriding the location to use those cities I find another bug: the reverse geocoder I'm using returns the names using foreign characters that cannot be read by the Pebble. It is not clear why they are showing up as latin characters on your device, and I'm worried that in trying to fix the bug on my end I'll break something.

**Comment by mattrossman** [comment]
Give v1.6.0 a shot, I'm dynamically sizing the text boxes on that row so there shouldn't be any more collisions between the temperature, city name, and sunrise/sunset time. I also switched the reverse geocoder to resolve that issue I mentioned above about foreign characters, so you might see the city names showing up slightly differently.
