### ISSUE TITLE
Battery level incorrect when loading watch after battery level has changed

### ISSUE THREAD

**Issue by clach04** [mattrossman/forecaswatch2#29]
I think this is true for all battery level changes but I'm documenting what I saw today:

* watch battery low, 20%
* exit out of FCW2
* load a different watchface
* charge pebble (to 100%)
* load FCW2 - battery still shows as low, eventually it will update

This appears to be due to the watchface persisting and then reading the battery level to storage. I'm not sure why it does this. I'll attach a quick fix but I think the persistence code should be removed.

**Comment by clach04** [comment]
Recommend removing:
* https://github.com/mattrossman/forecaswatch2/blob/master/src/c/appendix/persist.c#L36 - note this makes direct persistence calls rather than to `persist_set_battery_level()`
* https://github.com/mattrossman/forecaswatch2/blob/master/src/c/appendix/persist.c#L105
* https://github.com/mattrossman/forecaswatch2/blob/master/src/c/appendix/persist.c#L153

**Comment by mattrossman** [comment]
Good catch. I think the reason I persisted the battery level was because I was dead set on using the battery level that I already received from `battery_state_service_subscribe` rather than making another call to `battery_state_service_peek`. In hindsight, peeking the battery level is probably more efficient than saving and accessing from storage.

I'll merge that in and remove the persistence stuff sometime soon.

**Comment by clach04** [comment]
I've been thinking about this. I still think my quick fix is the best thing for now. One idea would be to refactor the persist battery code to use a static/global variable then the peek in my quick fix could be removed.

That way the form would be the same but the location and name of the function calls would be the same.

**Comment by mattrossman** [comment]
Included in v1.11.0
