### ISSUE TITLE
Calendar date number repeats upon month changing 

### ISSUE THREAD

**Issue by arcaderaid** [mattrossman/forecaswatch2#44]
I noticed this morning (October 25 2020) that the calendar dates displayed:
18 19 20 21 22 23 24
[25] 26 27 28 29 30 31
1 1 2 3 4 5 6

This appears due to the calendar month rotating from a month ending with 31 days on a Saturday. The big was easily remedied by going to another screen and coming back to the watch face. The calendar properly set to:
18 19 20 21 22 23 24
[25] 26 27 28 29 30 31
1 2 3 4 5 6 7

**Comment by arromdee** [comment]
This issue is not caused by 31 day months.  It is caused by daylight savings time.

The program finds the next day by adding and subtracting multiples of 24 hours.  If the time is between midnight and 1 AM, and the clocks are being set back, 24 hours after 12:01 AM Sunday is 11:01 still on Sunday,

I have a patch for this as well as for making Sundays and/or Saturdays red based on a setting.  I have no idea what to do with it--should I mail it to the maintainer?  Attach it here?

**Comment by mattrossman** [comment]
@arromdee good catch! You can submit your patch as a pull request against the `develop` branch of this repository. I'll review it and merge it in once everything looks good.

**Comment by arromdee** [comment]
I submitted a patch which 1) fixes this bug and 2) adds the requested ability to make Sundays red (along with Saturdays and US Federal holidays).

**Comment by mattrossman** [comment]
Thanks for the patch, it's included in [v1.15.0](https://github.com/mattrossman/forecaswatch2/releases/tag/v1.15.0)
