### ISSUE TITLE
"Today highlight" color does not work any more (as of v1.16.0)

### ISSUE THREAD

**Issue by vukisoft** [mattrossman/forecaswatch2#46]
It always remains white whatever I set.

**Comment by mattrossman** [comment]
Thanks for letting me know.

This introduces a design question: now that the color of the today box gets affected by your choice of saturday/sunday/holiday colors, should the "today highlight" setting take priority over those? Or should it only apply to days that are otherwise white?

E.g. if your "today highlight" is set to yellow and "saturday color" set to blue, which one of these should you see:
<div>
<img style="display:inline-block;vertical-align: middle;" src="https://user-images.githubusercontent.com/22670878/98005898-9161d900-1dbf-11eb-8840-57f19f543aea.png" />
<img style="display:inline-block;vertical-align: middle;" src="https://user-images.githubusercontent.com/22670878/98007073-f5d16800-1dc0-11eb-9e09-a641e7a86498.png" />
</div>

For the left option, the box would turn yellow only on weekdays. I know in the original FCW2 today's box would change color to match the weekends, but it also didn't give the option for a custom highlight color. I can make an argument for either case, what do you think? Or do you not plan on using custom weekend colors?

**Comment by vukisoft** [comment]
I love the custom weekend colors, I don't have to count anymore which day it is on weekdays :)

I think either case is fine and justifiable .. I'd vote for the second (right) one though, reason is that I want to see clearly which day it is, color of the column will tell me which day it is.

**Comment by mattrossman** [comment]
I agree that the second option has better visibility. You mentioned that you can tell what day it is by looking at the color of other dates in the column. That works for weekends, but on holidays only a single date gets colored, so the user won't be able to tell if today is a holiday.

Perhaps a solution is to set the default "today highlight" to black, and have this be a special value that behaves like the left image. If the user selects any other highlight value (e.g. yellow), it will override to that color as in the right image. I'm choosing black as the special value because some users might want to have the "today highlight" to always white, but I can't imagine anyone would highlight the day black (it would appear as not highlighted). I can make a note of this behavior on the config page.

This way I can accommodate both the users who care about holidays and those who prioritize the "today" visibility.

**Comment by vukisoft** [comment]
Compromise! Add a switch if user wants the today highlight color or use the day's color for highlight :)

BTW "US holidays" should have an option to switch off, I'm not in the US so I don't want to see them at all :)

Or alternatively add an URL option for calendar subscription so we can use in other countries.
For example I'm using https://www.officeholidays.com/ics/united-kingdom/england in google calendar

**Comment by mattrossman** [comment]
Resolved in v1.17.0

I went with the approach of having the black value function as the default color matching behavior, any other value overrides this. Didn't want to add an extra switch just for this.

I also added a note to clarify that leaving the US holidays on white effectively disables them. It would be handy to have custom calendars loaded in but it's not something I'll have the time to implement.
